/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        Vehicle vehicleA = new Vehicle("AE86", "Toyota");
        Vehicle vehicleB = new Vehicle("GT-R", "NISSAN");
        vehicleA.speedUp(50);
        vehicleB.speedUp(100);


        Car car = new Car("A new car", "Yamaha");
        car.speedUp(180);
        car.speedUp(250);
    }
}

class Vehicle {
    private String name;
    private String brand;

    public Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }

    public void speedUp(int speed){
        System.out.println(String.format("A car with name: %s, brand: %s has speed up to %d!!!!!!!!!!!", this.name, this.brand, speed));
    }
}

class Car extends Vehicle {
    private String name;
    private String brand;

    public Car(String name, String brand){
        super(name, brand);
    }

    @Override
    public void speedUp(int speed){
        if (speed <= 200) {
            super.speedUp(speed);
        } else {
            System.out.println("Speed exist limitation! This car failed to speed up!");
        }
    }
}

class Bus extends Vehicle {
    private String name;
    private String brand;

    public Bus(String name, String brand){
        super(name, brand);
    }

    @Override
    public void speedUp(int speed){
        if (speed <= 80) {
            super.speedUp(speed);
        } else {
            System.out.println("Speed exist limitation! This bus failed to speed up!");
        }
    }
}