/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

class Vehicle {
    private String name;
    private String brand;

    public Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }

}